-- Creating tables for Migration-FlowDB

CREATE TABLE Region(
	region_no int NOT NULL,
	region_name varchar(20) NOT NULL,
	PRIMARY KEY(region_no),
	FOREIGN KEY(region_no) REFERENCES State(region_no)
);

SELECT * FROM Region

CREATE TABLE Housing_and_Income(
	state_no int NOT NULL,
	median_income double NOT NULL,
	median_housing_cost double NOT Null,
	median_home_value double NOT NULL,
	median_RE_taxes double NOT NULL,
	PRIMARY KEY(state_no),
	--FOREIGN KEY(state_no) REFERENCES State(state_no)
);
SELECT * FROM Housing_and_Income

--DROP TABLE CA_Migration_2Other_States CASCADE;

	-- More Tables: CA Migration to Other States by Year
CREATE TABLE CA2010_to_States(
year int Not Null,
	Abroad double Not Null,
	Washington double Not Null,
	Texas double Not Null,
	New_York double Not Null,
	Arizona double Not Null,
	Oregon double Not Null,
	Florida	double Not Null,
	Nevada double Not Null,
	Illinois double Not Null,
	Colorado double Not Null,
	Virginia double Not Null,
	Massachusetts double Not Null,
	Ohio double Not Null,
	Hawaii double Not Null,
	Pennsylvania double Not Null,
	Georgia double Not Null,
	New_Jersey double Not Null,
	North_Carolina double Not Null,
	Maryland double Not Null,
	Michigan double Not Null,
	Utah double Not Null,
	Tennessee double Not Null,
	Missouri double Not Null,
	Connecticut double Not Null,
	Indiana double Not Null,
	Minnesota double Not Null,
	Wisconsin double Not Null,
	District_of_Columbia double Not Null,
	Oklahoma double Not Null,
	South_Carolina double Not Null,
	Kansas double Not Null,
	Alabama double Not Null,
	Louisiana double Not Null,
	Idaho double Not Null,
	New_Mexico double Not Null,
	Nebraska double Not Null,
	Arkansas double Not Null,
	Montana double Not Null,
	Iowa double Not Null,
	Mississippi double Not Null,
	Alaska double Not Null,
	Kentucky double Not Null,
	North_Dakota double Not Null,
	Rhode_Island double Not Null,
	Vermont double Not Null,
	Wyoming double Not Null,
	South_Dakota double Not Null,
	Maine double Not Null,
	West_Virginia double Not Null,
	Delaware double Not Null,
	New_Hampshire double Not Null,
	PRIMARY KEY (year)
);

CREATE TABLE CA2011_to_States(
	year int Not Null,
	Abroad double Not Null,
	Washington double Not Null,
	Texas double Not Null,
	New_York double Not Null,
	Arizona double Not Null,
	Oregon double Not Null,
	Florida	double Not Null,
	Nevada double Not Null,
	Illinois double Not Null,
	Colorado double Not Null,
	Virginia double Not Null,
	Massachusetts double Not Null,
	Ohio double Not Null,
	Hawaii double Not Null,
	Pennsylvania double Not Null,
	Georgia double Not Null,
	New_Jersey double Not Null,
	North_Carolina double Not Null,
	Maryland double Not Null,
	Michigan double Not Null,
	Utah double Not Null,
	Tennessee double Not Null,
	Missouri double Not Null,
	Connecticut double Not Null,
	Indiana double Not Null,
	Minnesota double Not Null,
	Wisconsin double Not Null,
	District_of_Columbia double Not Null,
	Oklahoma double Not Null,
	South_Carolina double Not Null,
	Kansas double Not Null,
	Alabama double Not Null,
	Louisiana double Not Null,
	Idaho double Not Null,
	New_Mexico double Not Null,
	Nebraska double Not Null,
	Arkansas double Not Null,
	Montana double Not Null,
	Iowa double Not Null,
	Mississippi double Not Null,
	Alaska double Not Null,
	Kentucky double Not Null,
	North_Dakota double Not Null,
	Rhode_Island double Not Null,
	Vermont double Not Null,
	Wyoming double Not Null,
	South_Dakota double Not Null,
	Maine double Not Null,
	West_Virginia double Not Null,
	Delaware double Not Null,
	New_Hampshire double Not Null,
	PRIMARY KEY (year)
);

CREATE TABLE CA2012_to_States(
	year int Not Null,
	Abroad double Not Null,
	Washington double Not Null,
	Texas double Not Null,
	New_York double Not Null,
	Arizona double Not Null,
	Oregon double Not Null,
	Florida	double Not Null,
	Nevada double Not Null,
	Illinois double Not Null,
	Colorado double Not Null,
	Virginia double Not Null,
	Massachusetts double Not Null,
	Ohio double Not Null,
	Hawaii double Not Null,
	Pennsylvania double Not Null,
	Georgia double Not Null,
	New_Jersey double Not Null,
	North_Carolina double Not Null,
	Maryland double Not Null,
	Michigan double Not Null,
	Utah double Not Null,
	Tennessee double Not Null,
	Missouri double Not Null,
	Connecticut double Not Null,
	Indiana double Not Null,
	Minnesota double Not Null,
	Wisconsin double Not Null,
	District_of_Columbia double Not Null,
	Oklahoma double Not Null,
	South_Carolina double Not Null,
	Kansas double Not Null,
	Alabama double Not Null,
	Louisiana double Not Null,
	Idaho double Not Null,
	New_Mexico double Not Null,
	Nebraska double Not Null,
	Arkansas double Not Null,
	Montana double Not Null,
	Iowa double Not Null,
	Mississippi double Not Null,
	Alaska double Not Null,
	Kentucky double Not Null,
	North_Dakota double Not Null,
	Rhode_Island double Not Null,
	Vermont double Not Null,
	Wyoming double Not Null,
	South_Dakota double Not Null,
	Maine double Not Null,
	West_Virginia double Not Null,
	Delaware double Not Null,
	New_Hampshire double Not Null,
	PRIMARY KEY (year)
);
CREATE TABLE CA2013_to_States(
	year int Not Null,
	Abroad double Not Null,
	Washington double Not Null,
	Texas double Not Null,
	New_York double Not Null,
	Arizona double Not Null,
	Oregon double Not Null,
	Florida	double Not Null,
	Nevada double Not Null,
	Illinois double Not Null,
	Colorado double Not Null,
	Virginia double Not Null,
	Massachusetts double Not Null,
	Ohio double Not Null,
	Hawaii double Not Null,
	Pennsylvania double Not Null,
	Georgia double Not Null,
	New_Jersey double Not Null,
	North_Carolina double Not Null,
	Maryland double Not Null,
	Michigan double Not Null,
	Utah double Not Null,
	Tennessee double Not Null,
	Missouri double Not Null,
	Connecticut double Not Null,
	Indiana double Not Null,
	Minnesota double Not Null,
	Wisconsin double Not Null,
	District_of_Columbia double Not Null,
	Oklahoma double Not Null,
	South_Carolina double Not Null,
	Kansas double Not Null,
	Alabama double Not Null,
	Louisiana double Not Null,
	Idaho double Not Null,
	New_Mexico double Not Null,
	Nebraska double Not Null,
	Arkansas double Not Null,
	Montana double Not Null,
	Iowa double Not Null,
	Mississippi double Not Null,
	Alaska double Not Null,
	Kentucky double Not Null,
	North_Dakota double Not Null,
	Rhode_Island double Not Null,
	Vermont double Not Null,
	Wyoming double Not Null,
	South_Dakota double Not Null,
	Maine double Not Null,
	West_Virginia double Not Null,
	Delaware double Not Null,
	New_Hampshire double Not Null,
	PRIMARY KEY (year)
);
CREATE TABLE CA2014_to_States(
	year int Not Null,
	Abroad double Not Null,
	Washington double Not Null,
	Texas double Not Null,
	New_York double Not Null,
	Arizona double Not Null,
	Oregon double Not Null,
	Florida	double Not Null,
	Nevada double Not Null,
	Illinois double Not Null,
	Colorado double Not Null,
	Virginia double Not Null,
	Massachusetts double Not Null,
	Ohio double Not Null,
	Hawaii double Not Null,
	Pennsylvania double Not Null,
	Georgia double Not Null,
	New_Jersey double Not Null,
	North_Carolina double Not Null,
	Maryland double Not Null,
	Michigan double Not Null,
	Utah double Not Null,
	Tennessee double Not Null,
	Missouri double Not Null,
	Connecticut double Not Null,
	Indiana double Not Null,
	Minnesota double Not Null,
	Wisconsin double Not Null,
	District_of_Columbia double Not Null,
	Oklahoma double Not Null,
	South_Carolina double Not Null,
	Kansas double Not Null,
	Alabama double Not Null,
	Louisiana double Not Null,
	Idaho double Not Null,
	New_Mexico double Not Null,
	Nebraska double Not Null,
	Arkansas double Not Null,
	Montana double Not Null,
	Iowa double Not Null,
	Mississippi double Not Null,
	Alaska double Not Null,
	Kentucky double Not Null,
	North_Dakota double Not Null,
	Rhode_Island double Not Null,
	Vermont double Not Null,
	Wyoming double Not Null,
	South_Dakota double Not Null,
	Maine double Not Null,
	West_Virginia double Not Null,
	Delaware double Not Null,
	New_Hampshire double Not Null,
	PRIMARY KEY (year)
);
CREATE TABLE CA2015_to_States(
	year int Not Null,
	Abroad double Not Null,
	Washington double Not Null,
	Texas double Not Null,
	New_York double Not Null,
	Arizona double Not Null,
	Oregon double Not Null,
	Florida	double Not Null,
	Nevada double Not Null,
	Illinois double Not Null,
	Colorado double Not Null,
	Virginia double Not Null,
	Massachusetts double Not Null,
	Ohio double Not Null,
	Hawaii double Not Null,
	Pennsylvania double Not Null,
	Georgia double Not Null,
	New_Jersey double Not Null,
	North_Carolina double Not Null,
	Maryland double Not Null,
	Michigan double Not Null,
	Utah double Not Null,
	Tennessee double Not Null,
	Missouri double Not Null,
	Connecticut double Not Null,
	Indiana double Not Null,
	Minnesota double Not Null,
	Wisconsin double Not Null,
	District_of_Columbia double Not Null,
	Oklahoma double Not Null,
	South_Carolina double Not Null,
	Kansas double Not Null,
	Alabama double Not Null,
	Louisiana double Not Null,
	Idaho double Not Null,
	New_Mexico double Not Null,
	Nebraska double Not Null,
	Arkansas double Not Null,
	Montana double Not Null,
	Iowa double Not Null,
	Mississippi double Not Null,
	Alaska double Not Null,
	Kentucky double Not Null,
	North_Dakota double Not Null,
	Rhode_Island double Not Null,
	Vermont double Not Null,
	Wyoming double Not Null,
	South_Dakota double Not Null,
	Maine double Not Null,
	West_Virginia double Not Null,
	Delaware double Not Null,
	New_Hampshire double Not Null,
	PRIMARY KEY (year)
);
CREATE TABLE CA2016_to_States(
	year int Not Null,
	Abroad double Not Null,
	Washington double Not Null,
	Texas double Not Null,
	New_York double Not Null,
	Arizona double Not Null,
	Oregon double Not Null,
	Florida	double Not Null,
	Nevada double Not Null,
	Illinois double Not Null,
	Colorado double Not Null,
	Virginia double Not Null,
	Massachusetts double Not Null,
	Ohio double Not Null,
	Hawaii double Not Null,
	Pennsylvania double Not Null,
	Georgia double Not Null,
	New_Jersey double Not Null,
	North_Carolina double Not Null,
	Maryland double Not Null,
	Michigan double Not Null,
	Utah double Not Null,
	Tennessee double Not Null,
	Missouri double Not Null,
	Connecticut double Not Null,
	Indiana double Not Null,
	Minnesota double Not Null,
	Wisconsin double Not Null,
	District_of_Columbia double Not Null,
	Oklahoma double Not Null,
	South_Carolina double Not Null,
	Kansas double Not Null,
	Alabama double Not Null,
	Louisiana double Not Null,
	Idaho double Not Null,
	New_Mexico double Not Null,
	Nebraska double Not Null,
	Arkansas double Not Null,
	Montana double Not Null,
	Iowa double Not Null,
	Mississippi double Not Null,
	Alaska double Not Null,
	Kentucky double Not Null,
	North_Dakota double Not Null,
	Rhode_Island double Not Null,
	Vermont double Not Null,
	Wyoming double Not Null,
	South_Dakota double Not Null,
	Maine double Not Null,
	West_Virginia double Not Null,
	Delaware double Not Null,
	New_Hampshire double Not Null,
	PRIMARY KEY (year)
);
CREATE TABLE CA2017_to_States(
	year int Not Null,
	Abroad double Not Null,
	Washington double Not Null,
	Texas double Not Null,
	New_York double Not Null,
	Arizona double Not Null,
	Oregon double Not Null,
	Florida	double Not Null,
	Nevada double Not Null,
	Illinois double Not Null,
	Colorado double Not Null,
	Virginia double Not Null,
	Massachusetts double Not Null,
	Ohio double Not Null,
	Hawaii double Not Null,
	Pennsylvania double Not Null,
	Georgia double Not Null,
	New_Jersey double Not Null,
	North_Carolina double Not Null,
	Maryland double Not Null,
	Michigan double Not Null,
	Utah double Not Null,
	Tennessee double Not Null,
	Missouri double Not Null,
	Connecticut double Not Null,
	Indiana double Not Null,
	Minnesota double Not Null,
	Wisconsin double Not Null,
	District_of_Columbia double Not Null,
	Oklahoma double Not Null,
	South_Carolina double Not Null,
	Kansas double Not Null,
	Alabama double Not Null,
	Louisiana double Not Null,
	Idaho double Not Null,
	New_Mexico double Not Null,
	Nebraska double Not Null,
	Arkansas double Not Null,
	Montana double Not Null,
	Iowa double Not Null,
	Mississippi double Not Null,
	Alaska double Not Null,
	Kentucky double Not Null,
	North_Dakota double Not Null,
	Rhode_Island double Not Null,
	Vermont double Not Null,
	Wyoming double Not Null,
	South_Dakota double Not Null,
	Maine double Not Null,
	West_Virginia double Not Null,
	Delaware double Not Null,
	New_Hampshire double Not Null,
	PRIMARY KEY (year)
);
CREATE TABLE CA2018_to_States(
	year int Not Null,
	Abroad double Not Null,
	Washington double Not Null,
	Texas double Not Null,
	New_York double Not Null,
	Arizona double Not Null,
	Oregon double Not Null,
	Florida	double Not Null,
	Nevada double Not Null,
	Illinois double Not Null,
	Colorado double Not Null,
	Virginia double Not Null,
	Massachusetts double Not Null,
	Ohio double Not Null,
	Hawaii double Not Null,
	Pennsylvania double Not Null,
	Georgia double Not Null,
	New_Jersey double Not Null,
	North_Carolina double Not Null,
	Maryland double Not Null,
	Michigan double Not Null,
	Utah double Not Null,
	Tennessee double Not Null,
	Missouri double Not Null,
	Connecticut double Not Null,
	Indiana double Not Null,
	Minnesota double Not Null,
	Wisconsin double Not Null,
	District_of_Columbia double Not Null,
	Oklahoma double Not Null,
	South_Carolina double Not Null,
	Kansas double Not Null,
	Alabama double Not Null,
	Louisiana double Not Null,
	Idaho double Not Null,
	New_Mexico double Not Null,
	Nebraska double Not Null,
	Arkansas double Not Null,
	Montana double Not Null,
	Iowa double Not Null,
	Mississippi double Not Null,
	Alaska double Not Null,
	Kentucky double Not Null,
	North_Dakota double Not Null,
	Rhode_Island double Not Null,
	Vermont double Not Null,
	Wyoming double Not Null,
	South_Dakota double Not Null,
	Maine double Not Null,
	West_Virginia double Not Null,
	Delaware double Not Null,
	New_Hampshire double Not Null,
	PRIMARY KEY (year)
);

SELECT * FROM CA2013_to_States;

--From Pandas to SQL Table
SELECT * FROM housingcost_by_statename;


---Combine CA Tables using a Union
 CREATE TABLE combined_CA_data
  AS
  SELECT * FROM CA2018_to_States UNION
  SELECT * FROM CA2017_to_States UNION 
  SELECT * FROM CA2016_to_States UNION 
  SELECT * FROM CA2015_to_States UNION
  SELECT * FROM CA2014_to_States UNION
  SELECT * FROM CA2013_to_States UNION 
  SELECT * FROM CA2012_to_States UNION 
  SELECT * FROM CA2011_to_States UNION
  SELECT * FROM CA2010_to_States
  ORDER BY Year ASC;


CREATE TABLE States_with_Highest_MedianHousing(
	Year int Not Null,
	NAME varchar Not Null,
	Median_Housing_Cost bigint Not Null
);

--DROP TABLE States_with_Highest_MedianHousing CASCADE;
SELECT * FROM States_with_Highest_MedianHousing



--- Query Data
--Left Join on CA2017_to_States and CA2018_to_States
SELECT CA2018_to_States.Year,
		CA2018_to_States.Oregon,
		CA2018_to_States.Alabama,
		CA2018_to_States.Texas,
		CA2018_to_States.North_Carolina,
		CA2018_to_States.Tennessee,
		CA2017_to_States.Abroad
FROM CA2018_to_States
LEFT JOIN CA2017_to_States
ON  CA2018_to_States.Year = CA2017_to_States.Year;
		
--- States with the highest Housing Cost
SELECT * From States_with_Highest_MedianHousing
WHERE Median_Housing_Cost >= 2200;


SELECT * From States_with_Highest_MedianHousing
WHERE (Median_Housing_Cost  BETWEEN '2200' AND '2400')
AND (Year BETWEEN '2016' AND '2018');

--Create New Tables with Previous Queries Using the SELECT INTO statement
SELECT NAME, Median_Housing_Cost
INTO analysis_info
FROM States_with_Highest_MedianHousing
WHERE (Median_Housing_Cost  BETWEEN '1800' AND '3000')
AND (Year BETWEEN '2015' AND '2018')

SELECT * FROM CA_Analysis;

SELECT Year, Texas, Arizona, North_Carolina, Idaho
INTO CA_analysis
FROM combined_ca_data
WHERE(Year BETWEEN '2015' AND '2018')
ORDER BY Year ASC;